/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_infernumvii_NativeConsole */

#ifndef _Included_com_infernumvii_NativeConsole
#define _Included_com_infernumvii_NativeConsole
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_infernumvii_NativeConsole
	 * Method:    readCharImmediately
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_infernumvii_NativeConsole_readCharImmediately
	(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif